### ISSUE TITLE
Browser has gone after update

### ISSUE THREAD

**Issue by rp9or** [CarudiBu/SubUI-browser#6]
My ZFlip 3 has just updated to Android 12 and OneUI 4.0.

The cover screen widget has vanished and I can't add it back as it doesn't appear on the widget list. 

I  have tried reinstalling the latest package but no luck.

Any advice welcomed.

**Comment by CarudiBu** [comment]
Hi! Unfortunately, Samsung has patched the workaround that this app uses in OneUI 4.0. I'm working on a fix for this app, but another developer has also created an app (https://play.google.com/store/apps/details?id=apps.ijp.coveros) that allows custom widgets and launching custom apps (including browsers) on the cover screen, even on OneUI 4.0, which you could use to a similar effect as this app.

**Comment by rp9or** [comment]
Thanks for letting me know, and thanks for the link to cover OS
